### ISSUE TITLE
there is an error occurs while exec search.py.   could anybody help me?

### ISSUE THREAD

**Issue by gogo03** [kakaobrain/fast-autoaugment#31]
1.cp search.py ../search.py

2.in the directory.    ..../fast-autoaugment
exec the flowing command:
python search.py -c confs/wresnet40x2_cifar10_b512.yaml

got the error.
46%|████████████████████████████████████████████████████████████████████████▎                                                                                      | 91/200 [30:06<00:30,  3.54it/s, cv1=200, cv2=200, cv3=90, cv4=200, cv5=200](pid=31751) 
(pid=31751) 0200]:  80%|████████  | 16/20 [00:04<00:01,  3.63it/s, loss=0.299, top1=0.905, top5=0.997]
(pid=31751) 0200]:  90%|█████████ | 18/20 [00:04<00:00,  4.60it/s, loss=0.298, top1=0.905, top5=0.997]
 46%|████████████████████████████████████████████████████████████████████████▎                                                                                      | 91/200 [30:07<00:30,  3.54it/s, cv1=200, cv2=200, cv3=90, cv4=200, cv5=200](pid=31751) 
[*test 0000/0200]: 100%|██████████| 20/20 [00:06<00:00,  3.31it/s, loss=0.298, top1=0.904, top5=0.997]
(pid=31751) 2019-12-26 15:58:24,892	ERROR worker.py:433 -- SystemExit was raised from the worker
(pid=31751) Traceback (most recent call last):
(pid=31751)   File "python/ray/_raylet.pyx", line 711, in ray._raylet.task_execution_handler
(pid=31751)   File "python/ray/_raylet.pyx", line 694, in ray._raylet.execute_task
(pid=31751) SystemExit: 0
170500096it [30:00, 94677.34it/s]
 46%|████████████████████████████████████████████████████████████████████████▎

**Comment by gogo03** [comment]
when I use the following command line.
the error is disappeared.
python search.py -c confs/wresnet40x2_cifar10_b512.yaml --cv_ratio 0.1

**Comment by heartInsert** [comment]
Hi ,man .  I   can  only  get   a  single   2080Ti  ,    the  errors  say    `It requires {GPU: 4.000000}, {CPU: 1.000000} for execution and {GPU: 4.000000}, {CPU: 1.000000} for placement, however there are no nodes in the cluster that can provide the requested resources`
 do  you   know  which  code  should  I  change  in  order  to   solve this ?
Thanks

**Comment by alexlyzhov** [comment]
@heartInsert Try to change `@ray.remote(num_gpus=4, max_calls=1)` to `@ray.remote(num_gpus=1, max_calls=1)` in `search.py`.

**Comment by heartInsert** [comment]
@nikkou 
Thanks  for your  help  ,  I  run  it  successful. :)

**Comment by xiesong521** [comment]
> confs/wresnet40x2_cifar10_b512.yaml



> 1.cp search.py ../search.py
> 
> 2.in the directory. ..../fast-autoaugment
> exec the flowing command:
> python search.py -c confs/wresnet40x2_cifar10_b512.yaml
> 
> got the error.
> 46%|████████████████████████████████████████████████████████████████████████▎ | 91/200 [30:06<00:30, 3.54it/s, cv1=200, cv2=200, cv3=90, cv4=200, cv5=200](pid=31751)
> (pid=31751) 0200]: 80%|████████ | 16/20 [00:04<00:01, 3.63it/s, loss=0.299, top1=0.905, top5=0.997]
> (pid=31751) 0200]: 90%|█████████ | 18/20 [00:04<00:00, 4.60it/s, loss=0.298, top1=0.905, top5=0.997]
> 46%|████████████████████████████████████████████████████████████████████████▎ | 91/200 [30:07<00:30, 3.54it/s, cv1=200, cv2=200, cv3=90, cv4=200, cv5=200](pid=31751)
> [*test 0000/0200]: 100%|██████████| 20/20 [00:06<00:00, 3.31it/s, loss=0.298, top1=0.904, top5=0.997]
> (pid=31751) 2019-12-26 15:58:24,892 ERROR worker.py:433 -- SystemExit was raised from the worker
> (pid=31751) Traceback (most recent call last):
> (pid=31751) File "python/ray/_raylet.pyx", line 711, in ray._raylet.task_execution_handler
> (pid=31751) File "python/ray/_raylet.pyx", line 694, in ray._raylet.execute_task
> (pid=31751) SystemExit: 0
> 170500096it [30:00, 94677.34it/s]
> 46%|████████████████████████████████████████████████████████████████████████▎

hi ,where is the file confs/wresnet40x2_cifar10_b512.yaml ?I can't find it? thanks
