### ISSUE TITLE
No module named 'watch'

### ISSUE THREAD

**Issue by wudlike** [kakaobrain/fast-autoaugment#70]
I have installed pystopwatch2, and when i run code:
python search.py -c confs/wresnet40x2_cifar10_b512.yaml --dataroot ... --redis ...
I got an error shown below:

Traceback (most recent call last):
  File "search.py", line 139, in <module>
    from pystopwatch2 import PyStopwatch
  File "/usr/local/lib/python3.7/dist-packages/pystopwatch2/__init__.py", line 1, in <module>
    from watch import PyStopwatch
ModuleNotFoundError: No module named 'watch'

please how to solve this problem??

**Comment by jiangwenj02** [comment]
[from pystopwatch2.watch import PyStopwatch](https://github.com/ildoonet/pystopwatch2/commit/64ecd49a2a164b665f44c54d7015b0f7d8497b7e)

**Comment by kgstutwh** [comment]
You can solve it as follows:
`pip install git+https://github.com/ildoonet/pystopwatch2.git@64ecd49a2a164b665f44c54d7015b0f7d8497b7e`
